version: '3.8'

services:
  # rabbitMQ
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "15672:15672"  # web management UI (http://localhost:15672)
      - "5672:5672"    # application connection port
    volumes: # disable logging
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    networks:
      - ransom_net
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Zookeeper (for Kafka)
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - ransom_net

  # Kafka
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - ransom_net

  # detection service
  detection-service:
    build: .
    container_name: detection-service
    command: python -m detection.detection
    volumes:
      - .:/app  # mount current source code; changes take effect after restart
      - ./shared_logs:/logs
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - ransom_net

#  # recovery Service
#  recovery-service:
#    build: .
#    container_name: recovery-service
#    command: python ./recovery/recovery.py
#    volumes:
#      - .:/app
#      - ./recovery/recovery_logs:/logs # file writing log, for further recovery
#    depends_on:
#      - backup-storage
#    networks:
#      - ransom_net

  # backup storage
  backup-storage:
    build: .
    container_name: backup-storage
    command: python ./recovery/backup_server.py
    volumes:
      - ./recovery/backup:/data
    networks:
      - ransom_net

  # 4 replications of finance department
  # client: finance1
  client-finance1:
    build: .
    container_name: client-finance1
    hostname: client-finance1
    command: >
      sh -lc '
        set -e;
        echo "[client] checking restic repo...";
        restic snapshots >/dev/null 2>&1 || restic init;
        echo "[client] restic repo ok";
        exec python -m client.client_server
      '
    expose:
      - "50051"  # gRPC Lockdown port
      - "4321"
    ports:
      - "5001:5000" # file browser & swagger
    environment:
      - CLIENT_ID=finance1
      - MONITOR_DIR=/data
      - PEERS=client-finance2:4321,client-finance3:4321,client-finance4:4321
      - RESTIC_REPOSITORY=rest:http://finance1:12345678@rest-server:8000/finance1/finance1
      - RESTIC_PASSWORD_FILE=/run/secrets/restic_repo_pass
    volumes:
      - .:/app
      - ./secrets/restic_repo_pass_finance:/run/secrets/restic_repo_pass:ro
      - ./simulation_data/finance1:/data:delegated # Mount simulated data
      - ./shared_logs:/logs  
    depends_on:
      rabbitmq:
        condition: service_healthy
      rest-server:
        condition: service_healthy
    networks:
      - ransom_net

  # client: finance2
  client-finance2:
    build: .
    container_name: client-finance2
    hostname: client-finance2
    command: >
      sh -lc '
        set -e;
        echo "[client] checking restic repo...";
        restic snapshots >/dev/null 2>&1 || restic init;
        echo "[client] restic repo ok";
        exec python -m client.client_server
      '
    expose:
      - "50051"  # gRPC Lockdown port
      - "4321"
    environment:
      - CLIENT_ID=finance2
      - MONITOR_DIR=/data
      - PEERS=client-finance1:4321,client-finance3:4321,client-finance4:4321
      - RESTIC_REPOSITORY=rest:http://finance2:12345678@rest-server:8000/finance2/finance2
      - RESTIC_PASSWORD_FILE=/run/secrets/restic_repo_pass
    volumes:
      - .:/app
      - ./secrets/restic_repo_pass_finance:/run/secrets/restic_repo_pass:ro
      - ./simulation_data/finance2:/data:delegated # Mount simulated data
      - ./shared_logs:/logs  
    depends_on:
      rabbitmq:
        condition: service_healthy
      rest-server:
        condition: service_healthy
    networks:
      - ransom_net

  # client: finance3
  client-finance3:
    build: .
    container_name: client-finance3
    hostname: client-finance3
    command: >
      sh -lc '
        set -e;
        echo "[client] checking restic repo...";
        restic snapshots >/dev/null 2>&1 || restic init;
        echo "[client] restic repo ok";
        exec python -m client.client_server
      '
    expose:
      - "50051"  # gRPC Lockdown port
      - "4321"
    environment:
      - CLIENT_ID=finance3
      - MONITOR_DIR=/data
      - PEERS=client-finance1:4321,client-finance2:4321,client-finance4:4321
      - RESTIC_REPOSITORY=rest:http://finance3:12345678@rest-server:8000/finance3/finance3
      - RESTIC_PASSWORD_FILE=/run/secrets/restic_repo_pass
    volumes:
      - .:/app
      - ./secrets/restic_repo_pass_finance:/run/secrets/restic_repo_pass:ro
      - ./simulation_data/finance3:/data:delegated # Mount simulated data
      - ./shared_logs:/logs  
    depends_on:
      rabbitmq:
        condition: service_healthy
      rest-server:
        condition: service_healthy
    networks:
      - ransom_net

  # client: finance4
  client-finance4:
    build: .
    container_name: client-finance4
    hostname: client-finance4
    command: >
      sh -lc '
        set -e;
        echo "[client] checking restic repo...";
        restic snapshots >/dev/null 2>&1 || restic init;
        echo "[client] restic repo ok";
        exec python -m client.client_server
      '
    expose:
      - "50051"  # gRPC Lockdown port
      - "4321"
    environment:
      - CLIENT_ID=finance4
      - MONITOR_DIR=/data
      - PEERS=client-finance2:4321,client-finance3:4321,client-finance1:4321
      - RESTIC_REPOSITORY=rest:http://finance4:12345678@rest-server:8000/finance4/finance4
      - RESTIC_PASSWORD_FILE=/run/secrets/restic_repo_pass
    volumes:
      - .:/app
      - ./secrets/restic_repo_pass_finance:/run/secrets/restic_repo_pass:ro
      - ./simulation_data/finance4:/data:delegated # Mount simulated data
      - ./shared_logs:/logs  
    depends_on:
      rabbitmq:
        condition: service_healthy
      rest-server:
        condition: service_healthy
    networks:
      - ransom_net

  # attacker
  # attacker-node:
  #   build: .
  #   container_name: attacker-node
  #   command: python attacker.py
  #   ports:
  #     - "8080:8080"  # http://localhost:8080
  #   volumes:
  #     - .:/app
  #   networks:
  #     - ransom_net
  
  # dashboard
  dashboard-node:
    build: .
    container_name: dashboard-node
    working_dir: /app/dashboard
    command: python dashboard.py
    ports:
      - "8501:8501"  # frontend dashboard
    volumes:
      - .:/app
      - ./shared_logs:/logs  
    networks:
      - ransom_net

  # finance-gateway
  finance-gateway:
    build: .
    container_name: finance-gateway
    command: python ./gateway/gateway.py
    ports:
      - "9000:9000" # gateway swagger
    environment:
      - STORAGE_NODES=client-finance1,client-finance2,client-finance3,client-finance4
    volumes:
      - .:/app
    networks:
      - ransom_net

  # restic repository HTTP backend
  rest-server:
    image: restic/rest-server:latest
    container_name: rest-server
    command:
      [
        "rest-server",
        "--path", "/data",
        "--listen", "0.0.0.0:8000",
        "--private-repos",
        "--htpasswd-file", "/run/secrets/htpasswd"
      ]
    volumes:
      - ./secure_backups/restic_repos:/data
      - ./secure_backups/restic_repos/.htpasswd:/run/secrets/htpasswd:ro
    networks:
      - ransom_net
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8000/ >/dev/null 2>&1 || exit 0"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  ransom_net:
    driver: bridge
